[package]
name = "cargo-hakari-regenerate"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/davidmaple/fluent-voice"
readme = "../../README.md"
description = "High-performance workspace-hack regeneration tool using cargo-hakari API"
keywords = ["cargo", "hakari", "workspace", "dependencies", "optimization"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "cargo-hakari-regenerate"
path = "src/main.rs"

[lib]
name = "cargo_hakari_regenerate"
path = "src/lib.rs"

[dependencies]
# Core hakari integration
# # fluent-voice-workspace-hack = { path = "../../workspace-hack" }
cargo-hakari = "0.9.36"
cargo_metadata = "0.21.0"

# Async runtime
tokio = { version = "1.47", features = ["rt", "sync", "macros", "rt-multi-thread", "fs"], default-features = false }

# CLI and user interface
clap = { version = "4.5", features = ["derive", "color", "suggestions"] }
console = "0.16.0"
indicatif = "0.18.0"

# Error handling and logging
anyhow = "1"
thiserror = "2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# Serialization and configuration
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1"
toml_edit = "0.23"
toml = "0.9"

# File system operations
walkdir = "2.5.0"
tempfile = "3.20.0"
memmap2 = "0.9.7"

# Safety and cleanup
scopeguard = "1.2.0"

# Performance optimizations
smallvec = { version = "2.0.0-alpha.11", features = ["serde"] }
regex = "1.11.1"
fluent-voice-workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
tokio-test = "0.4.4"
tempfile = "3.20.0"
