[package]
name = "fluent_voice_vad"
version = "0.1.0"
edition = "2024"
description = "Voice Activity Detection (VAD) for speech processing and audio analysis"
license = "Apache-2.0"
repository = "https://github.com/davidmaple/fluent-voice"
readme = "README.md"
keywords = ["speech", "stt","recognition", "voice", "activity", "detection"]
categories = ["multimedia::audio"]

[dependencies]
# fluent-voice-workspace-hack = { path = "../../workspace-hack" }
fluent_voice_domain = { path = "../domain" }

futures = "0.3.31"
# ndarray = "0.16" # in workspace-hack
ort = { path = "../../forks/ort", optional = true, features = ["ndarray"] }
pin-project = "1.1.10"
thiserror = "2"
typed-builder = "0.21"
ndarray = "0.16.1"

# Candle ML dependencies
candle-core = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-nn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-transformers = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }

# — Optional acceleration dependencies —
half = { version = "2.6.0", optional = true }

# Platform-specific acceleration dependencies
cudarc = { version = "0.17", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
metal = { version = "0.32.0", optional = true }
bindgen_cuda = { version = "0.1.5", optional = true }
candle-kernels = { git = "https://github.com/huggingface/candle", branch = "main", optional = true }
candle-metal-kernels = { git = "https://github.com/huggingface/candle", branch = "main", optional = true }
fluent-voice-workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
hound = "3.5.1"
# itertools = "0.14" # in workspace-hack
# tokio = { version = "1.45.1", features = ["rt", "sync", "macros"] } # in workspace-hack
tokio-stream = "0.1.17"

[features]
default = ["ort"]

# --- Candle backend features (required for all candle crates) -----
cuda = ["dep:cudarc", "dep:bindgen_cuda", "dep:candle-kernels", "candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
cudnn = ["cuda", "cudarc/cudnn"]
metal = ["dep:metal", "dep:candle-metal-kernels", "candle-core/metal", "candle-nn/metal", "candle-transformers/metal"]
accelerate = ["dep:accelerate-src", "candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl", "candle-transformers/mkl"]

# --- Other features ---
async = []
load-dynamic = ["ort/load-dynamic"]
ort = ["dep:ort"]

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3.2", optional = true }

[lib]
path = "src/lib.rs"
name = "fluent_voice_vad"
