[package]
name = "fluent-voice-samples"
edition.workspace = true
version.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
indicatif = "0.18.0"
jwalk = "0.8.1"
log = "0.4.28"
rayon = "1"
serde = { version = "1.0.225", features = ["derive"] }
serde_yaml = "0.9.34"
symphonia = { version = "0.5.4", features = ["mp3"] }
thiserror = "2"
fluent-voice-workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
tempfile = "3.22.0"
