use fluent_voice_macros::{stt_engine, tts_engine};
use futures_core::Stream;
use std::pin::Pin;
use std::task::{Context, Poll};

// Import necessary traits for testing
use fluent_voice::speaker::Speaker;
use fluent_voice::speaker_builder::{SpeakerBuilder, SpeakerExt};
use fluent_voice::stt_conversation::SttConversationExt;
use fluent_voice::stt_engine::SttEngine;
use fluent_voice::tts_conversation::TtsConversationExt;
use fluent_voice::tts_engine::TtsEngine;

// Simple test stream types
pub struct TestAudioStream;

impl Stream for TestAudioStream {
    type Item = i16;

    fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Poll::Ready(None) // Simple empty stream for testing
    }
}

impl Unpin for TestAudioStream {}

// Test segment type that implements TranscriptSegment
#[derive(Clone, Debug, Default)]
pub struct TestSegment {
    pub text: String,
    pub start_ms: u32,
    pub end_ms: u32,
    pub speaker_id: Option<String>,
}

impl fluent_voice::transcript::TranscriptSegment for TestSegment {
    fn start_ms(&self) -> u32 {
        self.start_ms
    }

    fn end_ms(&self) -> u32 {
        self.end_ms
    }

    fn text(&self) -> &str {
        &self.text
    }

    fn speaker_id(&self) -> Option<&str> {
        self.speaker_id.as_deref()
    }
}

pub struct TestTranscriptStream;

impl Stream for TestTranscriptStream {
    type Item = Result<TestSegment, fluent_voice::voice_error::VoiceError>;

    fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Poll::Ready(None) // Simple empty stream for testing
    }
}

impl Unpin for TestTranscriptStream {}

// Simple transcript type for testing
#[derive(Clone, Debug, Default)]
pub struct TestTranscript {
    pub segments: Vec<TestSegment>,
}

// Generate TTS engine using macro
tts_engine! {
    engine = TestTtsEngine,
    voice = String,
    audio = TestAudioStream,
    /// Test TTS engine generated by macro
}

// Generate STT engine using macro
stt_engine! {
    engine = TestSttEngine,
    segment = TestSegment,
    stream = TestTranscriptStream,
    transcript = TestTranscript,
    /// Test STT engine generated by macro
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_tts_macro_compilation() {
        // Test that the TTS macro generates compilable code
        let _engine = TestTtsEngine;

        // Test builder creation (using trait)
        let _builder = TestTtsEngine::builder();

        // Test engine instance (using trait)
        let engine = TestTtsEngine;
        let _conv_builder = engine.conversation();
    }

    #[tokio::test]
    async fn test_stt_macro_compilation() {
        // Test that the STT macro generates compilable code
        let _engine = TestSttEngine;

        // Test builder creation (using trait)
        let _builder = TestSttEngine::builder();

        // Test engine instance (using trait)
        let engine = TestSttEngine;
        let _conv_builder = engine.conversation();
    }

    #[tokio::test]
    async fn test_tts_speaker_creation() {
        // Test speaker creation using the generated engine
        let speaker = TestTtsEngine::speaker("Alice")
            .speak("Hello, world!")
            .build();

        assert_eq!(speaker.id(), "Alice");
    }

    #[test]
    fn test_macro_types_are_send_sync() {
        // Test that generated types have required bounds
        fn assert_send<T: Send>() {}
        fn assert_sync<T: Sync>() {}
        fn assert_send_sync<T: Send + Sync>() {}

        assert_send_sync::<TestTtsEngine>();
        assert_send_sync::<TestSttEngine>();
    }
}
