[package]
name = "cyterm"
version = "0.1.0"
edition = "2024"
authors = ["David Maple<david@cyrup.ai>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/davidmaple/fluent-voice"
description = "Software-rendered Ratatui terminal with Candle Whisper ASR, Silero VAD, and embedded wake-word spotting."
readme = "README.md"
default-run = "cyterm"

[dependencies]
fluent-voice-workspace-hack = { path = "../../workspace-hack" }

koffee = { path = "../koffee" }
fluent_voice_whisper = { path = "../whisper" }

ratatui = { git = "https://github.com/ratatui/ratatui", branch = "main" }
cosmic-text = "0.14.2"

cpal = "0.16.0"
# rubato              = { version = "0.16", features = ["fft_resampler"] } # in workspace-hack

# ndarray             = "0.16" # in workspace-hack
typed-builder = "0.21"

# Missing dependencies needed by src files
rustfft = "6.4"
rand = { version = "0.9", features = ["alloc", "std"] }
anyhow = "1.0"

candle-core = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-nn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-transformers = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }

# — Optional acceleration dependencies —
half = { version = "2.6", optional = true }

# Platform-specific acceleration dependencies
cudarc = { version = "0.17", optional = true, default-features = false, features = [
    "cublas",
    "cublaslt",
    "cudnn",
    "curand",
    "dynamic-linking",
    "f16",
    "std",
] }
metal = { version = "0.32", optional = true }
bindgen_cuda = { version = "0.1.5", optional = true }
candle-kernels = { git = "https://github.com/huggingface/candle", branch = "main", optional = true }
candle-metal-kernels = { git = "https://github.com/huggingface/candle", branch = "main", optional = true }
tokenizers = "0.22"
once_cell = "1.21"


pin-project = "1.1"

crossbeam-channel = "0.5.15"
crossbeam-utils = "0.8.21"
ndarray = "0.16.1"

log = "0.4.27"
serde = { version = "1.0", features = ["derive"] }
ort = { path = "../../forks/ort" }
progresshub = { path = "../../../progresshub/packages/progresshub" }
thiserror = "2.0"
fluent_voice = { path = "../fluent-voice" }
dirs = "6.0.0"
progresshub-client-http = { version = "0.1.0", path = "../../../progresshub/packages/client_http" }
tokio = { version = "1.47.1", features = ["full"] }
rand_distr = "0.5.1"

[dev-dependencies]
hound = "3.5.1"
# itertools           = "0.14" # in workspace-hack
# tokio               = { version = "1.45.1", features = ["rt", "sync", "macros"] } # in workspace-hack
tokio-stream = "0.1"

# tracing             = "0.1.41" # in workspace-hack
tracing-chrome = "0.7.2"
tracing-subscriber = "0.3.19"

[features]
default = ["microphone", "metal"]

# --- Candle backend features (required for all candle crates) -----
cuda = [
    "cudarc",
    "dep:bindgen_cuda",
    "dep:candle-kernels",
    "candle-core/cuda",
    "candle-nn/cuda",
    "candle-transformers/cuda",
]
cudnn = ["cuda", "cudarc/cudnn"]
metal = [
    "dep:metal",
    "dep:candle-metal-kernels",
    "candle-core/metal",
    "candle-nn/metal",
    "candle-transformers/metal",
]
accelerate = [
    "dep:accelerate-src",
    "candle-core/accelerate",
    "candle-nn/accelerate",
    "candle-transformers/accelerate",
]
mkl = [
    "dep:intel-mkl-src",
    "candle-core/mkl",
    "candle-nn/mkl",
    "candle-transformers/mkl",
]

# --- Audio features ---
microphone = []
encodec = []
mimi = []
snac = []
# Async support
async = []

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
intel-mkl-src = { version = "0.8", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
intel-mkl-src = { version = "0.8", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3", optional = true }
